### ISSUE TITLE
set -o pipefail doesn't work in sh but works in bash

### ISSUE THREAD

**Issue by conchoecia** [schatzlab/pseudohaploid#2]
The first few lines of `create_pseudohaploid.sh` are:

```
#!/bin/sh

set -o pipefail
```

but running the script returned the error `set: Illegal option -o pipefail`.

I changed the first line to:

```
#!/bin/bash
```

and everything worked fine. Ubuntu 16.04.

**Comment by mschatz** [comment]
Fixed. Good luck!
