### ISSUE TITLE
pseudohaploid.chains.pl error

### ISSUE THREAD

**Issue by tangerzhang** [schatzlab/pseudohaploid#3]
Hi Mike,
I am running pseudohaploid and found the error below in pseudohaploid.chains.pl script. Could you please help me out? Thanks!
```
Processing coords file (pseu80.filter.coords)...
  processed 10000 alignments
  processed 20000 alignments
  processed 30000 alignments
  processed 40000 alignments
  processed 50000 alignments
Argument "|" isn't numeric in numeric gt (>) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 43, <COOR
DS> line 56206.
Use of uninitialized value $qid in hash element at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 57, <C
OORDS> line 56206.
Argument "|" isn't numeric in numeric lt (<) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 59, <COOR
DS> line 56206.
Argument "|" isn't numeric in numeric gt (>) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 43, <COOR
DS> line 56207.
Use of uninitialized value $qid in hash element at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 57, <C
OORDS> line 56207.
Argument "|" isn't numeric in numeric lt (<) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 59, <COOR
DS> line 56207.
Argument "|" isn't numeric in numeric gt (>) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 43, <COOR
DS> line 56208.
Use of uninitialized value $qid in hash element at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 57, <C
OORDS> line 56208.
Argument "|" isn't numeric in numeric lt (<) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 59, <COOR
DS> line 56208.
Argument "|" isn't numeric in numeric gt (>) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 43, <COOR
DS> line 56209.
Use of uninitialized value $qid in hash element at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 57, <C
OORDS> line 56209.
Argument "|" isn't numeric in numeric lt (<) at /public/home/tanger/software/pseudohaploid//pseudohaploid.chains.pl line 59, <COOR
DS> line 56209.
```

**Comment by mschatz** [comment]
Hi,

Were you able to run the examples in the test directory? Im guessing that
you used slightly incorrect parameters for show-coords- it should be
"show-coords -rclH"
This will make sure the right columns are output

Cheers

Mike

**Comment by sunnycqcn** [comment]
Hello Mike,
I met the same error. I check the show-coords, I used show-corrds -rclH as you said.
Best,
Fuyou

**Comment by mschatz** [comment]
Hmmmm, which version of MUMmer are you using? I've only tested it with
MUMmer 3.x not the new 4.x series.

Are you able to run the examples in test/run_tests.sh. The output should
look like this:

$ ./run_tests.sh

Running the simple example
===============================================================
Generating pseudohaploid genome sequence
----------------------------------------
GENOME: simple.fa
OUTPREFIX: ph.simple
MIN_IDENTITY: 90
MIN_LENGTH: 1000
MIN_CONTAIN: 93
MAX_CHAIN_GAP: 20000

1. Aligning simple.fa to itself with nucmer
Original assembly has 2 contigs

2. Filter for alignments longer than 1000 bp and below 90 identity

3. Generating coords file

4. Identifying alignment chains: min_id: 90 min_contain: 93 max_gap: 20000
Processing coords file (ph.simple.filter.coords)...
Processed 6 alignment records [4 valid]
Finding chains for 2 contigs...
Found 2 total edges [0.000 constructtime, 0.000 searchtime, 4 stackadd]
Looking for contained contigs...
Found 1 joint contained contigs
Printed 1 total contained contigs

5. Generating a list of redundant contig ids using min_contain: 93
Identified 1 redundant contig to remove in ph.simple.contained.ids

6. Creating final pseudohaploid assembly in ph.simple.pseudohap.fa
Pseudohaploid assembly has 1 contigs

This should report: Pseudohaploid assembly has 1 contigs
===============================================================


Running the basic example
===============================================================
Generating pseudohaploid genome sequence
----------------------------------------
GENOME: basic.fa
OUTPREFIX: ph.basic
MIN_IDENTITY: 90
MIN_LENGTH: 1000
MIN_CONTAIN: 93
MAX_CHAIN_GAP: 20000

1. Aligning basic.fa to itself with nucmer
Original assembly has 4 contigs

2. Filter for alignments longer than 1000 bp and below 90 identity

3. Generating coords file

4. Identifying alignment chains: min_id: 90 min_contain: 93 max_gap: 20000
Processing coords file (ph.basic.filter.coords)...
Processed 8 alignment records [4 valid]
Finding chains for 4 contigs...
Found 2 total edges [0.000 constructtime, 0.000 searchtime, 4 stackadd]
Looking for contained contigs...
Found 1 joint contained contigs
Printed 1 total contained contigs

5. Generating a list of redundant contig ids using min_contain: 93
Identified 1 redundant contig to remove in ph.basic.contained.ids

6. Creating final pseudohaploid assembly in ph.basic.pseudohap.fa
Pseudohaploid assembly has 3 contigs

This should report: Pseudohaploid assembly has 3 contigs
===============================================================

Good luck

Mike

**Comment by tangerzhang** [comment]
Hi Mike,
I am using MUMmer version 3 as you suggested.
Yes, I am able to run the test data without any error reported.

**Comment by mschatz** [comment]
Hmm, can you send a sample of your coords file:

First just do head on the coords file

$ head *.filter.coords

And then do this so we can see around line 56206

$ head -56256 *.filter.coords | tail -100

Thanks!

Mike

**Comment by mschatz** [comment]
I just pushed a fix that should help with this.

Mike
