### ISSUE TITLE
sge_mummer

### ISSUE THREAD

**Issue by diriano** [schatzlab/pseudohaploid#4]
Hi,
what changes have to be made in create_pseudohaploid.sh in ordeer to use sge_mummer.
I tried changing the line:
  (nucmer --maxmatch -c 100 -l 500 $GENOME $GENOME -p $PREFIX) >& nucmer.log
with 
  (/data1/bioinfo/sge_mummer/sge_mummer.sh $GENOME $GENOME ${PREFIX}_tmp) >& nucmer.log
But then the test does not complete succesfully.
I will appreciate instructions on how to go ahead.
Thanks,
Diego

**Comment by mschatz** [comment]
Can you check if the output from nucmer and sge_mummer give the same
results in show-coords? You might have issues with sge_mummer's
configuration

Good luck!

Mike

**Comment by mschatz** [comment]
Ping me if this is still an issue
