### ISSUE TITLE
what is difference between pseudohaploid and purge_haplotigs?

### ISSUE THREAD

**Issue by baishengjun** [schatzlab/pseudohaploid#6]

**Comment by mschatz** [comment]
They have a similar goal, although they differ in implementation. It has
been my experience that there are a lot of data set specific
parameters that need to be optimized for either approach

Good luck

Mike

**Comment by baishengjun** [comment]
Thanks for your quick reply
you say pseudohaploid is similar to the approach used by FALCON-unzip,
can I use pseudohaploid first,then use purge_haplotigs for my genome ?

I try to use pseudohaploid on my genome just now,
it decrease my genome size from 530M to 490M before polishing , 
and I also use it after polishing ,it seems no change. what caused this phenomenon ?

Best,
Bai

**Comment by mschatz** [comment]
I would run either pseudohaploid or purse_haplotigs, but not both. Both
require parameter tuning to accommodate the characteristics of your
particular genome. Unfortunately we do not have an automated procedure for
that

Good luck

Mike
